# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pushes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='browser',
            name='user',
        ),
        migrations.AddField(
            model_name='browser',
            name='website',
            field=models.CharField(default=datetime.datetime(2016, 6, 25, 17, 14, 45, 862000, tzinfo=utc), max_length=150),
            preserve_default=False,
        ),
    ]
