# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 06:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pushes', '0003_remove_notification_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='browser',
        ),
        migrations.AddField(
            model_name='notification',
            name='website',
            field=models.CharField(default=datetime.datetime(2016, 6, 26, 6, 34, 14, 541000, tzinfo=utc), max_length=150),
            preserve_default=False,
        ),
    ]
